### PR TITLE
Use name in SecurityDefinition for headers

### PR DESCRIPTION
**Pull request by fmotrifork**
Fixes issue #41

### CODE REVIEW

**Comment by fmotrifork** [comment]
Usage example:

```
swagger {
    apiSource {
        ...
        securityDefinition {
            name = 'jwt'
            type = 'apiKey'
            keyName = 'Authorization'
            keyLocation = 'header'
        }
    }
}
```

**Comment by set321go** [comment]
👍 

Can you add a unit test as well please.

**Comment by gigaSproule** [comment]
I'm wondering if it makes sense to have more concrete implementations, so there is a JWT object where it can be validated against to ensure the correct fields are provided. Or maybe take the complete opposite approach and take in the closure and treat it as the JSON/YAML itself?

**Comment by fmotrifork** [comment]
I don't think it would be worth the effort to create actual objects for the three different security schemes handled in swagger v2 (BasicAuth, ApiKeyAuth and OAuth2).

I would rather go the closure way with inline JSON.

If we choose to rewrite the implementation we should also allow for defining more than one securityDefinition.

**Comment by gigaSproule** [comment]
All I was thinking is that this doesn't really help with OAuth right? Also, as you point out we aren't allowing for multiple security definitions as is allowed in the [OpenAPI specification](https://swagger.io/specification/#securityRequirementObject)

**Comment by fmotrifork** [comment]
Sure we should. But I really needed this fix. ;)
And this way allowed the change to be a non api breaking implementation.

I don’t think it would be much work to add OAuth as well, the same way as I did with ApiKey? And also add the possibility to configure more security definitions.

If we can merge this one now, I will see if I can find time to make another PR later. :D

**Comment by fmotrifork** [comment]
Could I also persuade you to release a 1.0.1 build with this extra feature in? :smile:

**Comment by gigaSproule** [comment]
You mean you want to actually use this?!

I've release 1.0.1

**Comment by mogensen** [comment]
Thank you sir.

**Comment by fmotrifork** [comment]
Thank you sir.

**Pull request merged**
