### PR TITLE
Add default tag when no tags on Api or Operation

### LINKED ISSUE #87: SpringMvc: Create default tags for @RestController
When no special annotations are provided all operations have no tags and the SwaggerUI will list them under default. 
In case of SpringMVC (and also JAXRS) operations are normally put into context with the class they belong. 
Allow to configure a property so that all operations within a class will have a tag with the SimpleClassName of the class they belong.

### PR DESCRIPTION
**Pull request by copa2**
Fixes #87 

A tag with the SimpleClassName of the controller will be created when no `@Api` is set.  
This tag will also be assigned to all methods/operations which have no tags.
So this works like `@Api.tags` are assigned to methods/operations.

### CODE REVIEW

**Comment by copa2** [comment]
I am not aware of similar cases. In my opinion this is more a fallback when somebody didn't define tags on `@Api`. So if somebody wants class name and their other tags they just can define them on `@Api.tags` or `@Operation.tags`. These take always precedence. 
It is possible to introduce an additional configuration property to enable/disable this fallback behavior.

**Comment by copa2** [comment]
JAX-RS has currently another default behavior. When not using swagger annotations and just having the JAX-RS annotations there are no path mappings in `swagger.json`. So you have to provide at least an `@Api` but then you can also provide directly the tags there.

**Comment by copa2** [comment]
JAX-RS default behavior is different. Without swagger annotations and just using JAX-RS annotation will not generate path mappings in `swagger.json`. So you have to add `@Api` on the Resource. But then you also can add the tags directly there.

**Comment by gigaSproule** [comment]
Sorry I'm late getting back to this. Won't this mean that if I don't want tags, I can't?

I also want to refactor the logic so that JAX-RS and Spring work in the same way. I'm not really a fan of the fact they kind of do the same thing, but not really.

**Comment by copa2** [comment]
Yes, new default would be that always tags are written. 
In my opinion this makes more sense than have no tags at all. Tags are used within the swagger UI to group together the operations. This is the same as a class in java does. So the grouping is also visible in the UI. 
But if you want we could introduce an additional configuration property which controls this. 

Regarding that JAX-RS and Spring currently are not on pair should probably we fixed in another issue.

**Comment by gigaSproule** [comment]
I think for now, we make it configurable and once the issue for sorting out parity between spring and JAX-RS, we can change that. I think there's an issue already open for sorting the readers, but in a field in the middle of nowhere, so can't check right now.

**Comment by copa2** [comment]
Ok added property `tagStrategy`. So tag generation can be controlled. If nothing is set behavior is like before. If you add `class` it will use this new strategy.

**Comment by gigaSproule** [comment]
Looks like your other PR has caused a conflict here.

**Pull request merged**
