### PR TITLE
Feature/remove maven code

### PR DESCRIPTION
**Pull request by gigaSproule**

### CODE REVIEW

**Comment by fmotrifork** [comment]
This pullrequest seems to reintroduce the bug that was solved here: "unknown property "classesDirs" #27"

**Comment by gigaSproule** [comment]
I'm not sure how, that hasn't changed. What version of Gradle are you using?

**Comment by fmotrifork** [comment]
Hmm.. Looking at the code I have to agree. But my output looks like this:

```
:generateSwaggerDocumentation FAILED
:generateSwaggerDocumentation (Thread[main,5,main]) completed. Took 0.27 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateSwaggerDocumentation'.
> Could not get unknown property 'classesDirs' for main classes of type org.gradle.api.internal.tasks.DefaultSourceSetOutput.

```

My gradle version:

```
$ ./gradlew --version

 ------------------------------------------------------------
Gradle 3.4
------------------------------------------------------------

Build time:   2017-02-20 14:49:26 UTC
Revision:     73f32d68824582945f5ac1810600e8d87794c3d4

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_161 (Oracle Corporation 25.161-b12)
OS:           Windows 7 6.1 amd64
```

**Comment by gigaSproule** [comment]
Fixed

**Comment by fmotrifork** [comment]
Perfect ! I have verified that this fix works with Gradle 3.4
Great work. :+1:

**Comment by gigaSproule** [comment]
And now for all the issues to arise!

**Comment by set321go** [comment]
I can chip in as i have a good idea how the plugin works!

**Pull request merged**
